const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),E=require('../src/engine.js'),c=require('../src/config.json'),original=require('./original-config.json');
const resultsDir=path.resolve(__dirname,'../test-results');fs.mkdirSync(resultsDir,{recursive:true});
const results=[];async function test(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS '+name);}catch(e){results.push({name,passed:false,error:e.stack});console.log('FAIL '+name+' '+e.stack);}}
(async()=>{
await test('All original learning activity/resource/quest/lesson values preserved',()=>{for(let w=0;w<24;w++)for(let a=0;a<original.weeks[w].activities.length;a++)for(const key of Object.keys(original.weeks[w].activities[a]))assert.deepEqual(c.weeks[w].activities[a][key],original.weeks[w].activities[a][key]);for(const key of ['resources','bonusMissions','leadershipLessons'])original[key].forEach((item,i)=>Object.keys(item).forEach(field=>assert.deepEqual(c[key][i][field],item[field])));});
await test('Nested malformed backup fields are rejected before rendering',()=>{for(const modify of [b=>b.progress.jobs.bad=null,b=>b.progress.baseline.rewards=[null],b=>b.progress.recovery=[{}],b=>b.progress.resources['resource-001']='invalid',b=>b.progress.retrospectives=[{text:'missing cycle'}]]){const b=E.fresh(c);modify(b);assert.throws(()=>E.validateBundle(b));}});
const browser=await chromium.launch({...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH}:{}),headless:true}),url=process.env.MC_TEST_URL||require('node:url').pathToFileURL(path.resolve(__dirname,'../index.html')).href;
await test('Focus returns to the originating activity after evidence save rerenders the page',async()=>{const context=await browser.newContext({viewport:{width:390,height:400}}),page=await context.newPage();await page.goto(url);await page.locator('#recommendations [data-action=activity]').first().click();await page.locator('#evidenceForm [name=note]').fill('SYNTHETIC focus test');await page.locator('#evidenceForm button[type=submit]').click();await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.getElementById('dialog').open && document.activeElement.dataset.action==='activity',{},{timeout:5000});assert.deepEqual(await page.evaluate(()=>({action:document.activeElement.dataset.action,id:document.activeElement.dataset.id})),{action:'activity',id:'act-01-01'});await context.close();});
await test('Failed storage message is visible inside the active dialog',async()=>{const context=await browser.newContext(),page=await context.newPage();await page.goto(url);await page.locator('#recommendations [data-action=activity]').first().click();await page.locator('#evidenceForm [name=note]').fill('SYNTHETIC pending evidence');await page.evaluate(()=>Storage.prototype.setItem=function(){throw Error('Synthetic quota failure');});await page.locator('#evidenceForm button[type=submit]').click();assert.match(await page.locator('#dialogError').innerText(),/Not saved.*Synthetic quota failure/);assert.equal(await page.locator('#dialogError').isVisible(),true);await context.close();});
await browser.close();fs.writeFileSync(path.join(resultsDir,'final-results.json'),JSON.stringify({runAt:new Date().toISOString(),results},null,2));if(results.some(x=>!x.passed))process.exitCode=1;
})();
