/* Vanilla browser application. The only persistent object is the versioned bundle. */
(()=>{
'use strict';
const E=Engine,$=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={command:'◈',missions:'◎',sidequests:'◇',operations:'↗',intel:'▤',recruit:'⌁',operative:'◉',achievements:'✧',leadership:'⌘',config:'⚙'};
let bundle=E.fresh(CONFIG),view='command',pending=null,lastRaw=null,readBlocked=false,damagedRaw=null,legacyRaw=null,notice='',lastFocus=null,lastFocusData=null,dialogActivity=null,sessionToken=null,configDraft=null,prepared=null;
const filters={mode:'all',track:'all',status:'all',query:'',quest:'all',leadership:'all',resource:''};
function btn(label,action,id='',cls=''){return `<button type="button" class="${cls}" data-action="${action}" data-id="${esc(id)}">${label}</button>`;}
function link(url,label){const safe=E.safeURL(url);return safe?`<a href="${esc(safe)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`:`<span class="muted">${esc(label)} (link unavailable)</span>`;}
function options(list,value){return list.map(x=>{const [v,l]=Array.isArray(x)?x:[x,x];return `<option value="${esc(v)}" ${v===value?'selected':''}>${esc(l)}</option>`;}).join('');}
function field(label,name,value,type='text',extra=''){return `<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function area(label,name,value,placeholder=''){return `<label>${esc(label)}<textarea name="${name}" placeholder="${esc(placeholder)}">${esc(value)}</textarea></label>`;}
function badges(a){return `<div class="chips">${(a.tracks||[]).map(t=>{const col=bundle.config.tracks.find(x=>x.code===t)?.color||'#65e7ee';return `<span class="chip track" style="--track:${col}">${esc(t)}</span>`;}).join('')}<span class="chip ${a.stretch||a.kind!=='plan'?'stretch':'core'}">${a.stretch||a.kind!=='plan'?'Optional stretch':'Core'}</span>${a.priority?'<span class="chip core">Priority</span>':''}</div>`;}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),2800);}
function download(name,data,type='application/json'){const blob=new Blob([typeof data==='string'?data:JSON.stringify(data,null,2)],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),20000);}
function status(text,error=false){$('saveStatus').textContent=text;$('saveStatus').className=error?'error':'signal';}
function renderNotice(){
 const q=bundle.progress.recovery.filter(q=>!q.resolved).length;
 $('saveNotice').innerHTML=(notice?`<div class="notice ${pending||readBlocked?'error':''}" role="alert"><strong>${pending?'Changes are NOT saved. ':readBlocked?'Recovery required. ':''}</strong>${esc(notice)}<div class="row">${pending?btn('Retry save','retry')+btn('Download unsaved backup','export-pending')+btn('Discard pending changes','discard'):''}${readBlocked?btn('Download original data','export-damaged')+btn('Try previous backup','previous')+btn('Import backup','import')+btn('Start fresh with recovery copy','recover-fresh'):''}${legacyRaw?btn('Review legacy migration','legacy'):''}</div></div>`:'')+(q?`<div class="notice">${q} legacy record${q===1?' needs':'s need'} mapping review. Original data is preserved. ${btn('Open recovery','recovery')}</div>`:'');
}
function save(candidate,{checkpoint=false,message='Saved on this device'}={}){
 if(readBlocked){notice='Stored data could not be read safely. Download it or restore a backup before saving.';renderNotice();return false;}
 try{
  E.validateBundle(candidate);
  const current=localStorage.getItem(E.KEY);if(current!==lastRaw)throw Error('A different tab changed this save. Download your unsaved backup, then reload to review the newer save.');
  candidate.revision=(bundle.revision||0)+1;candidate.savedAt=new Date().toISOString();
  if(checkpoint&&lastRaw)localStorage.setItem(E.KEY+'_previous',lastRaw);
  const text=JSON.stringify(candidate);localStorage.setItem(E.KEY,text);lastRaw=text;bundle=candidate;pending=null;notice='';legacyRaw=null;status(message+' · '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}));renderNotice();return true;
 }catch(e){pending=candidate;notice=e.message+' Your previous saved data has not been replaced by this pending change. Export the unsaved backup or retry.';status('Not saved · action needed',true);renderNotice();if($('dialog').open&&$('dialogError')){$('dialogError').textContent='Not saved. '+e.message+' Close this dialog to retry or download the unsaved backup.';$('dialogError').focus();}return false;}
}
function mutate(fn,opts={}){if(pending){toast('Resolve the pending save first.');return false;}const n=E.clone(bundle);try{const changed=fn(n);if(changed===false)return false;if(save(n,opts)){render();return true;}}catch(e){showError(e.message);}return false;}
function showError(text){const target=$('dialog').open?$('dialogError'):null;if(target){target.textContent=text;target.focus();}else{notice=text;renderNotice();}}
function openDialog(title,body){if(!$('dialog').open){lastFocus=document.activeElement;lastFocusData=lastFocus?.dataset?.action?{action:lastFocus.dataset.action,id:lastFocus.dataset.id}:null;}$('dialogContent').innerHTML=`<div class="dialog-head"><h2 id="dialogTitle">${esc(title)}</h2>${btn('✕','close','','close-button')}</div><div id="dialogError" class="error prewrap" role="alert" tabindex="-1"></div>${body}`;$('dialogContent').querySelector('.close-button').setAttribute('aria-label','Close dialog');if(!$('dialog').open)$('dialog').showModal();else $('dialogContent').querySelector('button').focus();}
function closeDialog(){if($('dialog').open)$('dialog').close();}
function navMarkup(){return bundle.config.views.map(v=>`<button data-action="view" data-id="${v.id}" ${view===v.id?'aria-current="page"':''}><span class="icon" aria-hidden="true">${icons[v.id]}</span>${esc(v.id==='command'?"Today's Focus":v.label)}</button>`).join('');}
function switchView(v){if(!bundle.config.views.some(x=>x.id===v))return;view=v;closeDialog();render();window.scrollTo(0,0);$('content').focus({preventScroll:true});}
function head(eyebrow,title,desc,actions=''){return `<div class="page-head"><div><div class="eyebrow">${esc(eyebrow)}</div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div>${actions?`<div class="row">${actions}</div>`:''}</div>`;}
function render(){
 document.title=bundle.config.meta.title+' · Mission Control '+bundle.appVersion;
 document.querySelector('.brand strong').textContent='◈ '+bundle.config.meta.title;
 document.querySelector('.mobilebar strong').textContent='◈ '+bundle.config.meta.title;
 $('nav').innerHTML=navMarkup();const s=bundle.progress.settings,w=bundle.config.weeks.find(w=>w.id===s.activeCycle);$('headerContext').textContent='CYCLE '+(w?.num||1)+' / '+bundle.config.weeks.length+' · YOUR PACE';
 const pages={command:focusPage,missions:planPage,sidequests:questsPage,operations:projectsPage,intel:resourcesPage,recruit:jobsPage,operative:profilePage,achievements:achievementsPage,leadership:leadershipPage,config:configPage};
 $('page').innerHTML=pages[view]();if(view==='config')$('configEditor').value=configDraft??JSON.stringify(bundle.config,null,2);renderNotice();
}
function focusPage(){
 const c=bundle.config,p=bundle.progress,s=p.settings,r=E.progression(bundle),rec=E.recommend(bundle),w=c.weeks.find(w=>w.id===s.activeCycle),core=w.activities.filter(a=>!a.stretch),done=core.filter(a=>E.record(bundle,a.id).completed).length;
 return head('COMMAND DECK / NEXT SESSION','A little time. A worthwhile mission.',p.profile.missionStatement||'Choose work that fits the day you actually have. One session is enough to move forward.',btn('Browse full plan','view','missions'))+
 `<section class="card featured"><div class="eyebrow">Set your flight window</div><h2>What fits today?</h2><form id="plannerForm"><div class="fields">${field('Weekly budget (hours)','weeklyHours',s.weeklyHours,'number','min="0" max="168" step="0.25" required')}${field('Next session (minutes)','sessionMinutes',s.sessionMinutes,'number','min="1" max="1440" required')}<label>Content format<select name="format">${options([['all','Any format'],['reading','Reading'],['hands-on','Hands-on'],['audio','Audio'],['video','Video'],['app','Mobile app']],s.format)}</select></label></div><fieldset><legend>Preferred tracks · choose any</legend><div class="track-checks">${c.tracks.map(t=>`<label class="check"><input type="checkbox" name="preferredTracks" value="${t.code}" ${s.preferredTracks.includes(t.code)?'checked':''}>${esc(t.code+' · '+t.name)}</label>`).join('')}</div></fieldset><div class="fields"><label>Active cycle<select name="activeCycle">${options(c.weeks.map(w=>[w.id,w.title]),s.activeCycle)}</select></label><label class="check"><input type="checkbox" name="includeStretch" ${s.includeStretch?'checked':''}>Include optional stretch work</label><button class="primary" type="submit">Find my next session →</button></div></form><div class="budget"><div class="split"><span><strong>${(rec.spent/60).toFixed(1)}h</strong> logged this week <span class="muted">/ ${s.weeklyHours}h budget</span></span><span class="green">${(rec.remaining/60).toFixed(1)}h available</span></div><div class="bar"><span style="width:${s.weeklyHours?Math.min(100,rec.spent/(s.weeklyHours*60)*100):0}%"></span></div><span class="small muted">Monday–Sunday, local days. Unused time does not become debt. Undated legacy hours stay in your history.</span></div></section>
 <div class="split"><h2>Your next move</h2><span class="small muted">${rec.items.length?rec.items.length+' options · choose one':'Room to adjust'}</span></div><p class="small muted">${esc(rec.reason)}</p>
 <div id="recommendations">${rec.items.map((x,i)=>`<article class="suggestion"><div class="index">0${i+1}</div><div>${badges(x.a)}<h3 style="margin-top:10px">${esc(x.a.title)}</h3><div class="row small"><span class="gold">${Math.round(x.minutes)} min session</span><span class="muted">${x.a.hrs}h original estimate · ${x.logged.toFixed(1)}h logged</span></div><p class="why">${x.reasons.map(esc).join(' · ')}</p><p class="small muted">${esc(x.mode.value)}${x.mode.inferred?' · inferred format, check the resource':''}<br>${esc(x.prerequisite.text)}</p>${x.a.projectIds?.length?`<p class="small green">Connects to ${x.a.projectIds.map(id=>esc(c.projects.find(p=>p.id===id)?.title)).join(', ')}</p>`:''}${x.estimate&&x.left<=0?'<p class="small warn">Estimate reached. Review the outcome; completion is your decision.</p>':''}</div><div class="actions">${btn('Open session →','activity',x.a.id,'primary')}${btn('Park for later','defer',x.a.id)}</div></article>`).join('')||'<div class="empty">There is no overdue queue. Choose a different format, return to parked work, or take the time you need.</div>'}</div>
 <div class="statrow"><div class="stat"><strong>${done}/${core.length}</strong><span>Core activities · cycle ${w.num}</span></div><div class="stat"><strong>${r.totalXP}</strong><span>XP · ${esc(c.rpg.ranks[Math.min(r.rank-1,c.rpg.ranks.length-1)])}</span></div><div class="stat"><strong>${Object.values(p.records).filter(x=>x.completed&&x.demonstrated&&(x.note||x.link||x.checkpoint)).length}</strong><span>Skills demonstrated · self-reported</span></div><div class="stat"><strong>${r.credsEarned}</strong><span>Credentials recorded with evidence</span></div></div>
 <div class="grid"><section class="card"><div class="eyebrow">CYCLE TELEMETRY</div><h3>${esc(w.phase)}</h3><p class="muted small">${done} core activities complete. Cycles advance only when you choose; calendar dates never create overdue work.</p>${btn('Review this cycle','view','missions')}</section><section class="card"><div class="eyebrow">Career signal</div><h3>Turn learning into something you can show.</h3><p class="muted small">Capture an example or checkpoint in the session log. Link it to a project, then use your reflections to tell the story.</p>${btn('Open projects','view','operations')}${btn('Write a reflection','retro',String(w.num))}</section></div>`;
}
function activityEntry(a){const r=E.record(bundle,a.id),m=E.mode(a),pr=E.prerequisite(bundle,a);return `<article class="entry ${r.completed?'done':''}" data-activity="${a.id}"><div class="split"><div><h3>${r.completed?'✓ ':r.deferred?'↳ ':''}${esc(a.title)}</h3>${badges(a)}</div>${btn(r.completed?'Review / undo':r.deferred?'Review parked work':'Open activity','activity',a.id)}</div><p class="small muted" style="margin:10px 0 0">${a.kind==='plan'?a.hrs+'h estimate · '+E.hours(bundle,a.id).toFixed(1)+'h logged · ':''}${esc(m.value)}${m.inferred?' (inferred)':''}${r.deferred?' · Parked for later':''} · ${esc(pr.text)}</p>${r.note?`<p class="small prewrap" style="margin-top:8px">${esc(r.note)}</p>`:''}<div class="resource-links">${(a.links||[]).map(l=>link(l.u,l.t)).join('')}${a.url?link(a.url,'Open resource'):''}</div></article>`;}
function planPage(){const c=bundle.config;return head('OPERATIONS PLAN / ALL CYCLES','Mission Board','Six domains, one flexible plan. Original weekday labels are suggestions. Core and stretch hours are counted separately.')+
 `<div class="card"><form id="planFilter"><div class="fields"><label>Format<select name="mode">${options(['all','reading','hands-on','audio','video','app'],filters.mode)}</select></label><label>Track<select name="track">${options(['all',...c.tracks.map(t=>t.code)],filters.track)}</select></label><label>Show<select name="status">${options([['all','All work'],['open','Unfinished'],['parked','Parked'],['done','Completed']],filters.status)}</select></label></div><button type="submit">Filter plan</button></form></div>`+c.weeks.map(w=>{
 const total=w.activities.reduce((n,a)=>n+a.hrs,0),core=w.activities.filter(a=>!a.stretch).reduce((n,a)=>n+a.hrs,0),list=E.all(c).filter(a=>a.cycleId===w.id).filter(a=>(filters.mode==='all'||E.mode(a).value===filters.mode)&&(filters.track==='all'||a.tracks.includes(filters.track))&&(filters.status==='all'||filters.status==='open'&&!E.record(bundle,a.id).completed||filters.status==='parked'&&E.record(bundle,a.id).deferred||filters.status==='done'&&E.record(bundle,a.id).completed));
 if(!list.length)return '';return `<details class="card cycle" data-cycle="${w.id}" ${w.id===bundle.progress.settings.activeCycle||filters.status==='parked'?'open':''}><summary>${esc(w.title)} <span class="muted">${w.activities.filter(a=>E.record(bundle,a.id).completed).length}/${w.activities.length} complete · ${core}h core + ${total-core}h stretch${total!==w.totalHrs?' · ⚠ '+total+'h derived / '+w.totalHrs+'h declared':''}</span></summary><div class="cycle-body">${btn('Make active cycle','cycle',w.id)}${w.checkpoint?`<div class="note"><strong>Checkpoint prompt:</strong> ${esc(w.checkpoint)}</div>`:''}${list.map(activityEntry).join('')}<div class="note">Resource availability, prices, credentials and descriptive claims are preserved from v7.8 and have not been verified as current.</div><form data-form="cycleNotes" data-id="${w.id}">${area('Cycle notes / checkpoint result','text',bundle.progress.cycleNotes[w.id]||'')}<div class="row" style="margin-top:12px"><button type="submit">Save cycle notes</button>${btn('Review bulk completion','bulk',w.id)}${btn('Write retrospective','retro',String(w.num))}</div></form></div></details>`;}).join('');}
function questsPage(){const list=E.all(bundle.config).filter(a=>a.kind==='quest'&&(filters.quest==='all'||a.track===filters.quest));return head('OPTIONAL EXPEDITIONS','Side Quests','Choose an extra challenge when it serves your goals. Completion and credential evidence are recorded separately.')+`<div class="note">All original resource, cost and certification claims below are unverified. Check the provider before committing time or money.</div><div class="row">${['all',...bundle.config.tracks.map(t=>t.code)].map(t=>btn(esc(t),'quest-filter',t,filters.quest===t?'primary':'')).join('')}</div>`+list.map(a=>`<div class="card" style="margin-top:16px">${activityEntry(a)}<p class="small muted">${esc(a.desc)}</p><span class="chip">${a.xp} XP on first completion</span> <span class="small warn">Original cost claim: ${esc(a.cost)} · unverified</span>${a.isCredential?'<p class="small gold">Credential opportunity · evidence required to record an award.</p>':''}</div>`).join('');}
function leadershipPage(){const list=E.all(bundle.config).filter(a=>a.kind==='leadership'&&(filters.leadership==='all'||a.cat===filters.leadership));return head('LEADERSHIP ACADEMY','Practice judgment. Grow influence.','Keep leadership development alongside technical work. Capture how a lesson changes a real conversation, decision or project.')+`<div class="note">Preserved descriptions, prices and availability are unverified. Reading a lesson does not certify a skill.</div><div class="row">${['all',...new Set(bundle.config.leadershipLessons.map(a=>a.cat))].map(t=>btn(esc(t),'leadership-filter',t,filters.leadership===t?'primary':'')).join('')}</div><div class="grid" style="margin-top:16px">`+list.map(a=>`<section class="card">${activityEntry(a)}<p class="small muted">${esc(a.desc)}</p><p class="small gold">${a.xp} XP · ${esc(a.cat)}${a.cost?' · original cost: '+esc(a.cost)+' (unverified)':''}</p></section>`).join('')+'</div>';}
function projectData(p){return bundle.progress.projects[p.id]||{status:'Not Started',github:'',video:'',demo:'',actualMetrics:'',subtasks:p.defaultTasks.map(t=>({...t,done:false}))};}
function projectsPage(){return head('OPERATIONS / PORTFOLIO','Build the proof.','Keep target metrics separate from results you have actually measured. Learning can support a project without proving its outcome.')+`<div class="note">Original project technologies and resource claims are preserved. Some project ideas mention external AI APIs; Mission Control itself requires none.</div><div class="grid">`+bundle.config.projects.map(p=>{const d=projectData(p),related=E.all(bundle.config).filter(a=>a.projectIds?.includes(p.id));return `<section class="card"><div class="eyebrow">${esc(p.id)} / ${esc(d.status)}</div><h2>${esc(p.title)}</h2><p class="muted">${esc(p.desc)}</p><div class="chips">${p.tech.map(t=>`<span class="chip">${esc(t)}</span>`).join('')}</div><div class="project-target"><strong>Target · not an achieved result</strong><br>${esc(p.metrics)}</div><form data-form="project" data-id="${p.id}"><label>Project status<select name="status">${options(['Not Started','In Progress','MVP Complete','Polished','Shipped'],d.status)}</select></label><div class="fields">${field('Repository link','github',d.github)}${field('Demo link','demo',d.demo)}${field('Video link','video',d.video)}</div>${area('Achieved results / measurement evidence','actualMetrics',d.actualMetrics,'What did you measure? Include conditions and a result link.')}<button style="margin-top:12px" type="submit">Save project</button></form><div class="resource-links">${['github','demo','video'].filter(k=>d[k]).map(k=>link(d[k],k)).join('')}</div><details><summary>Project checkpoints · ${d.subtasks.filter(t=>t.done).length}/${d.subtasks.length}</summary>${d.subtasks.map(t=>`<div class="subtask"><input type="checkbox" aria-label="Complete ${esc(t.text)}" data-task-project="${p.id}" data-task-id="${esc(t.id)}" ${t.done?'checked':''}><input type="text" aria-label="Checkpoint text" value="${esc(t.text)}" data-edit-project="${p.id}" data-edit-task="${esc(t.id)}">${btn('×','delete-task',p.id+'|'+t.id)}</div>`).join('')}${btn('+ Add checkpoint','add-task',p.id)}</details><details><summary>Learning connections</summary>${related.length?related.map(a=>`<div class="entry small">${E.record(bundle,a.id).completed?'✓ ':''}${esc(a.title)} ${btn('Open','activity',a.id)}</div>`).join(''):'<p class="small muted">No explicit activity links yet. Link a session to this project to build the connection.</p>'}<div class="note">Configured cross-domain relevance${Object.entries(p.crossover).map(([t,v])=>`<div><strong>${esc(t)}</strong> · ${esc(v)}</div>`).join('')}</div>${Object.entries(bundle.progress.records).filter(([id,r])=>r.projectId===p.id).map(([id,r])=>`<div class="entry small">${esc(E.all(bundle.config).find(a=>a.id===id)?.title||id)} · ${r.demonstrated?'demonstrated (self-reported)':'linked evidence'}<p>${esc(r.note)}</p></div>`).join('')}</details></section>`;}).join('')+'</div>';}
function resourcesPage(){const list=bundle.config.resources.filter(r=>(r.name+' '+r.cat+' '+r.url).toLowerCase().includes(filters.resource.toLowerCase()));return head('INTEL ARCHIVE','Your resource library','All original resources remain available. Price, availability and course claims are unverified; use the provider link to confirm.')+`<form id="resourceSearch" class="searchbar">${field('Search library','query',filters.resource,'search')}<button type="submit">Search resources</button></form><div class="grid">`+list.map(r=>`<section class="card"><h3>${esc(r.name)}</h3><p class="small muted">${esc(r.cat)} · ${esc(r.cost)} <span class="warn">(original claim, unverified)</span></p><div class="split">${link(r.url,'Open resource')}${btn(esc(bundle.progress.resources[r.id]||'N/A'),'resource-status',r.id)}</div></section>`).join('')+'</div>';}
function jobsPage(){return head('RECRUITMENT NETWORK','Connect the work to your next role.','Track conversations, applications and notes across all six domains. Listed companies are saved targets, not verified vacancies.')+bundle.config.jobTracks.map(t=>`<details class="card" ${t.code===bundle.config.jobTracks[0].code?'open':''}><summary>${esc(t.code+' · '+t.name)}</summary>${[...t.companies.map(c=>({id:c.id,company:c.name,...bundle.progress.jobs[c.id],track:t.code})),...Object.entries(bundle.progress.jobs).filter(([id,j])=>j.custom&&j.track===t.code).map(([id,j])=>({id,...j}))].map(j=>`<form class="entry" data-form="job" data-id="${j.id}" data-track="${t.code}"><h3>${esc(j.company)}</h3><div class="fields">${field('Company','company',j.company)}<label>Status<select name="status">${options(['Not Applied','Applied','Interviewing','Offer','Rejected'],j.status||'Not Applied')}</select></label>${field('Application date','dateApplied',j.dateApplied||'','date')}</div>${field('Contact','contact',j.contact||'')}${area('Notes','notes',j.notes||'')}<button style="margin-top:12px" type="submit">Save target</button></form>`).join('')}<div class="entry">${btn('+ Add company','add-company',t.code)}</div></details>`).join('');}
function profilePage(){const p=bundle.progress,r=E.progression(bundle),c=bundle.config;return head('OPERATIVE DOSSIER','Your progress, with a story behind it.','Activity completion, demonstrated skill and an earned credential each mean something different.',btn('Export portfolio','portfolio'))+
 `<section class="card"><form id="profileForm"><div class="fields">${field('Operative name','name',p.profile.name)}${field('Callsign','callsign',p.profile.callsign)}<label>Class<select name="classId">${options(c.rpg.classes.map(x=>[x.id,x.name]),p.profile.classId)}</select></label></div>${area('Mission statement','missionStatement',p.profile.missionStatement,'What do you want this learning to make possible?')}<p class="small muted">Class track bonuses affect stat gains; Pathfinder boosts plan XP by 5%. Side Quest and Academy XP equal their displayed awards. Existing completion awards keep their original rules.</p><label class="check"><input type="checkbox" name="quiet" ${p.settings.quiet?'checked':''}>Quiet mode</label><label class="check"><input type="checkbox" name="celebrate" ${p.settings.celebrate?'checked':''}>Show optional celebration banners (suppressed by quiet mode)</label><button type="submit">Save profile</button></form></section>
 <section class="card"><div class="eyebrow">CLEARANCE LEVEL ${r.rank}</div><h2>${esc(c.rpg.ranks[Math.min(r.rank-1,c.rpg.ranks.length-1)])}</h2><p>${r.totalXP} total XP · ${r.xp}/${r.next} toward the next level</p><div class="bar"><span style="width:${r.xp/r.next*100}%"></span></div><div class="statrow">${c.rpg.stats.map(s=>`<div class="stat"><strong>${r.stats[s.key]}</strong><span>${esc(s.name)} · display stat</span></div>`).join('')}</div><p class="small muted">${r.streak.count} consecutive active local days · ${r.streak.activeDays} active days recorded. Sessions count. Streaks do not multiply XP or make rest a penalty. Legacy UTC dates are retained in the archive and excluded from the new streak.</p>${p.migration?`<div class="note"><strong>Legacy opening balance: ${p.baseline.xp} XP.</strong> ${esc(p.migration.note)} Archived reported credentials: ${p.baseline.legacyCreds}. These are separate from evidence-backed records. ${btn('Export original legacy save','legacy-export')}</div>`:''}</section>
 <section class="card"><h2>Retrospectives</h2><p class="small muted">Write when useful. No unlock or catch-up requirement. Capture what changed, a piece of evidence, and your next small step.</p><div class="row">${[4,8,12,16,20,24].filter(n=>n<=Math.max(...c.weeks.map(w=>w.num))).map(n=>btn('After cycle '+n,'retro',String(n))).join('')}</div>${p.retrospectives.map(rt=>`<div class="entry"><h3>After cycle ${rt.atWeek} · ${esc(rt.date)}</h3><p class="prewrap">${esc(rt.text)}</p>${btn('Edit','retro',String(rt.atWeek))}</div>`).join('')}</section>
 <section class="card"><h2>Credentials recorded</h2><p class="small muted">Self-reported awards with an issuer and certificate ID or URL. Completing study or sitting an exam never records a credential automatically. Matching issuer/reference pairs count once.</p>${Object.entries(p.credentials).filter(([id,x])=>x.active).map(([id,x])=>`<div class="entry"><strong>${esc(x.title)}</strong><p>${esc(x.issuer)} · ${esc(x.date)}</p><p class="prewrap">${esc(x.reference)}</p>${btn('Withdraw record','credential-undo',id)}</div>`).join('')||'<p class="muted">No credential evidence recorded.</p>'}</section>
 <section class="card"><h2>Augmentations</h2><p>${r.augPoints} available point(s) · one at every fifth clearance level</p><p class="small muted">New installations are reversible. If XP is reversed below a level threshold, excess installations are suspended in purchase order, then reactivate when eligible. Legacy installations are preserved.</p><div class="grid">${c.rpg.augmentations.map(a=>{const installed=r.activeAugmentations.includes(a.id),suspended=r.suspended.some(x=>x.augmentationId===a.id),legacy=p.baseline.augmentations.includes(a.id),mechanical=['overclock','resource'].includes(a.id);return `<div class="card"><h3>${esc(a.icon+' '+a.name)}</h3><p class="small muted">${esc(a.mechanics||'No implemented effect. Cosmetic archive only.')}</p><p class="small">${legacy?'Legacy installation':suspended?'Suspended · level requirement':installed?'Installed':mechanical?'Available':'Cosmetic only · no points spent'}</p>${mechanical&&!legacy?btn(installed||suspended?'Uninstall + refund':'Install','augmentation',a.id):''}</div>`;}).join('')}</div></section>
 <section class="card"><h2>Recognition & XP ledger</h2><p class="small muted">Recognition is cosmetic and linked to a completion. Re-completing restores the same result; it never rerolls. Rest, meals and time off are always yours.</p><details><summary>Progression rules</summary><p class="small">Plan XP uses configured effort tiers, then stretch and class modifiers. No daily or streak multiplier. Side Quests and Leadership award exactly their configured XP. Each ${c.rpg.rules.categoryEvery} active new completions in a track adds ${c.rpg.rules.categoryXP} XP. Total XP, ranks and stats are derived together; undo recalculates them. Category threshold origins are assigned by stable activity ID, so completion order does not change the total. Credits, HP and MP do not create spendable resources.</p></details><div class="ledger">${Object.values(p.events).slice().reverse().map(e=>`<div class="entry"><div><strong>${esc(e.title)}</strong><br><span class="muted">${esc(e.id)} · ${e.legacy?'legacy opening balance':e.active?'active':'reversed'}</span>${e.reward?`<br>${esc(e.reward.tier+' · '+e.reward.reward)}`:''}</div><span class="gold nowrap">${e.active?'+':''}${e.xp} XP</span></div>`).join('')||'<p class="muted">Your first completion will appear here.</p>'}${r.bonuses.map(x=>`<div class="entry"><span>${esc(x.id)}<br><small>Origin: ${esc(x.origin)}</small></span><span>+${x.xp} XP</span></div>`).join('')}</div>${p.baseline.rewards.length?`<details><summary>Legacy reward archive · ${p.baseline.rewards.length}</summary><p class="small muted">Original rewards cannot be linked reliably to activities. They remain unchanged when any activity is reversed. Original rest/requisition wording is historical, not a restriction.</p>${p.baseline.rewards.map(x=>`<p class="small">${esc(x.date)} · ${esc(x.tier)} · ${esc(x.reward)}</p>`).join('')}</details>`:''}</section>`;
}
function achievementsPage(){const r=E.progression(bundle);return head('HALL OF VALOR','Recognize the work.','Current achievements are derived from active progress. Reversing a requirement removes only the achievement that no longer qualifies.')+`<div class="grid">${bundle.config.rpg.achievements.map(a=>`<section class="card achievement ${r.achievements.includes(a.id)?'earned':''}"><h3>${esc(a.icon+' '+a.name)}</h3><p>${esc(a.desc)}</p><span class="small ${r.achievements.includes(a.id)?'gold':'muted'}">${r.achievements.includes(a.id)?'Requirement met':'In progress'} · ${esc(a.condition)}</span></section>`).join('')}</div>${bundle.progress.baseline.achievements.length?`<div class="note">Legacy achievement archive (historical, unreconciled): ${bundle.progress.baseline.achievements.map(esc).join(', ')}</div>`:''}`;}
function configPage(){const v=E.validateConfig(bundle.config);return head('SYSTEMS / CONFIG & RECOVERY','Make the plan yours.','The complete active configuration is saved with its progress. IDs identify work permanently; keep them when moving or editing an activity.')+
 `<section class="card"><h2>Backup & recovery</h2><p class="muted">Back up before moving the HTML file or changing browser. Local files can have separate storage locations.</p><div class="row">${btn('↓ Full backup','export','', 'primary')}${btn('↑ Import / restore','import')}${btn('Restore previous snapshot','previous')}${btn('Review recovery records','recovery')}${btn('Export recovery archive','recovery-export')}</div>${bundle.progress.migration?btn('Export original legacy save','legacy-export'):''}<p class="small muted" style="margin-top:12px">Schema ${bundle.schemaVersion} · revision ${bundle.revision} · ${bundle.savedAt?'last saved '+esc(new Date(bundle.savedAt).toLocaleString()):'not yet saved'}</p></section>
 <section class="card"><h2>Full configuration</h2><p class="small muted">Exports include bonusMissions, leadershipLessons, views and every RPG section. An unchanged export can be applied. New activities need new unique IDs. A removed ID keeps its records in the archive; putting it back restores the same history. Use prerequisites: null for unknown, [] for explicitly none, or an array of activity IDs.</p><label for="configEditor">Configuration JSON</label><textarea id="configEditor" class="config-editor" spellcheck="false"></textarea><div class="row" style="margin-top:12px">${btn('Validate & preview changes','validate-config','','primary')}${btn('Export active config','export-config')}${btn('Load active config','load-config')}${btn('Preview default config','default-config')}${btn('New ID','new-id')}</div><div class="note">Current audit: ${v.errors.length} errors · ${v.warnings.filter(x=>x.includes('activities total')).length} cycle-hour discrepancies · ${v.warnings.filter(x=>x.includes('prerequisite')).length} missing prerequisite definitions. These are explicit planning cautions.</div><details><summary>Audit details</summary><div class="small prewrap">${v.warnings.map(esc).join('\n')}</div></details></section>`;
}
function activityDialog(id){const a=E.all(bundle.config).find(a=>a.id===id);if(!a)return showError('This activity is archived; restore its config ID to resume.');dialogActivity=id;sessionToken=E.uid('session');const r=E.record(bundle,id),h=E.hours(bundle,id),pr=E.prerequisite(bundle,a),sessions=bundle.progress.sessions.filter(s=>s.activityId===id),ev=bundle.progress.events[id];
 openDialog(a.title,`${badges(a)}<p class="small muted" style="margin-top:12px">${a.kind==='plan'?a.hrs+'h original estimate · '+h.toFixed(2)+'h logged':a.xp+' XP on first completion · effort estimate not configured'}<br>${esc(pr.text)}</p>${pr.blocked.length?`<div class="note">Configured prerequisite IDs: ${pr.blocked.map(esc).join(', ')}. The planner excludes this activity until these are complete. You can still record work already done.</div>`:''}<div class="resource-links">${(a.links||[]).map(l=>link(l.u,l.t)).join('')}${a.url?link(a.url,'Open resource'):''}</div><p class="small muted">Original resource claims and availability are unverified.</p>
 <form id="evidenceForm" data-id="${id}"><div class="stack">${area('What did you learn? / next step','note',r.note,'A sentence is enough. Where should you pick up next time?')}${field('Working example or project URL (optional)','link',r.link)}${area('Checkpoint result (optional)','checkpoint',r.checkpoint,'What worked? What is still unclear?')}<label>Connect this evidence to a project<select name="projectId">${options([['','No project selected'],...bundle.config.projects.map(p=>[p.id,p.title])],r.projectId||'')}</select></label><label class="check"><input type="checkbox" name="demonstrated" ${r.demonstrated?'checked':''}>Skill demonstrated · self-reported with evidence</label></div><p class="small muted">Demonstrated requires completion and a note, example link or checkpoint. Completion alone is not a credential.</p><div class="dialog-actions"><button type="submit">Save evidence</button>${btn(r.completed?'Undo completion':'Mark activity complete','complete',id,r.completed?'':'primary')}${btn(r.deferred?'Resume activity':'Park for later',r.deferred?'resume':'defer',id)}</div></form>
 <div class="entry"><h3>Log a session</h3><p class="small muted">Logging time keeps the original estimate and leaves completion unchanged.</p><form id="sessionForm" data-id="${id}" data-token="${sessionToken}"><div class="fields">${field('Minutes worked','minutes',bundle.progress.settings.sessionMinutes,'number','min="1" max="1440" required')}${field('Session note (optional)','note','')}<button type="submit" class="primary">Log session</button></div></form></div>
 ${a.isCredential||a.cat==='Cert'?`<div class="entry"><h3>Record a credential you actually earned</h3><p class="small muted">Use the same issuer and certificate reference if this award appears elsewhere in the plan; the count is deduplicated.</p><form id="credentialForm" data-id="${id}"><div class="fields">${field('Issuer','issuer','','text','required')}${field('Certificate ID or URL','reference','','text','required')}${field('Date earned','date',E.day(),'date','required')}</div><button type="submit">Record earned credential</button></form></div>`:''}
 <details class="entry"><summary>Session & activity history (${sessions.length} sessions)</summary>${sessions.map(s=>`<div class="entry small">${s.minutes} min · ${esc(s.localDay)} · ${s.active?'logged':'reversed'}<p class="prewrap">${esc(s.note)}</p>${s.active?btn('Undo this session','undo-session',s.id):''}</div>`).join('')}${bundle.progress.history.filter(e=>e.activityId===id).map(e=>`<p class="small muted">${esc(e.type)} · ${esc(e.localDay||e.at)} ${esc(e.reason||'')}</p>`).join('')}${ev?`<p class="small">Completion event: ${esc(ev.id)} · ${ev.xp} XP · ${ev.legacy?'preserved legacy balance':ev.active?'active':'reversed'}</p>`:''}${r.legacyHours?`<p class="small">${r.legacyHours} undated legacy hours preserved.</p>`:''}</details>`);
}
function captureEvidence(n,id){const f=$('evidenceForm');if(!f)return;const d=new FormData(f),r=n.progress.records[id]||(n.progress.records[id]=E.record(n,id)),linkValue=String(d.get('link')||'').trim();if(linkValue&&!E.safeURL(linkValue))throw Error('Example links must use http:// or https://.');const evidence={note:String(d.get('note')||''),link:linkValue,checkpoint:String(d.get('checkpoint')||''),projectId:String(d.get('projectId')||''),demonstrated:d.has('demonstrated')};if(evidence.demonstrated&&(!r.completed||!(evidence.note.trim()||evidence.link||evidence.checkpoint.trim())))throw Error('Mark completion and add a note, link or checkpoint before recording a demonstrated skill.');Object.assign(r,evidence);}
function deferDialog(id){const a=E.all(bundle.config).find(a=>a.id===id);openDialog('Park this activity',`<p>${esc(a?.title||id)}</p><p class="muted">It will leave Today’s Focus. Notes, time and history stay intact. Resume it from the Mission Board’s Parked filter whenever it fits.</p><form id="deferForm" data-id="${id}">${field('Reason / reminder (optional)','reason','')}<div class="dialog-actions"><button type="submit" class="primary">Park for later</button>${btn('Cancel','close')}</div></form>`);}
function retroDialog(atWeek){const r=bundle.progress.retrospectives.find(r=>String(r.atWeek)===String(atWeek));openDialog('Retrospective · after cycle '+atWeek,`<p class="muted">What changed? What can you show? What will you try next? Your words become your career narrative.</p><form id="retroForm" data-id="${esc(atWeek)}">${area('Reflection','text',r?.text||'')}<div class="dialog-actions"><button class="primary" type="submit">Save reflection</button></div></form>`);}
function configPreview(c){const v=E.validateConfig(c);if(v.errors.length){openDialog('Configuration needs attention',`<div class="prewrap error">${esc(v.errors.join('\n'))}</div><p>The active config and progress have not changed.</p>`);return;}prepared={kind:'config',value:c};const before=new Set(E.all(bundle.config).map(x=>x.id)),after=new Set(E.all(c).map(x=>x.id)),added=[...after].filter(x=>!before.has(x)),removed=[...before].filter(x=>!after.has(x));openDialog('Review configuration',`<p>${c.tracks.length} tracks · ${c.weeks.length} cycles · ${after.size} activities (including optional work).</p><p>${added.length} added IDs · ${removed.length} archived IDs. Matching IDs keep all progress. XP already awarded keeps its event snapshot; category thresholds use the active rules.</p>${removed.length?`<details><summary>IDs leaving the plan</summary><div class="prewrap">${removed.map(esc).join('\n')}</div></details>`:''}<div class="note">${v.warnings.length} planning cautions: missing prerequisites and/or cycle totals. These do not block application.</div><details><summary>Review cautions</summary><div class="small prewrap">${v.warnings.map(esc).join('\n')}</div></details><div class="dialog-actions">${btn('Apply validated configuration','confirm-config','','primary')}${btn('Cancel','close')}</div>`);}
function importPreview(value){if(value.schemaVersion===8){E.validateBundle(value);prepared={kind:'backup',value};openDialog('Restore full backup',`<p>This restores the saved configuration, progress, session history and recovery archive together.</p><p>${value.config.weeks.length} cycles · ${Object.values(value.progress.records).filter(x=>x.completed).length} completed records · ${E.progression(value).totalXP} XP.</p><p class="muted">Your current bundle will be kept as the previous snapshot when storage permits. Export it first if you want a separate copy.</p><div class="dialog-actions">${btn('Restore this backup','confirm-backup','','primary')}${btn('Export current backup','export')}${btn('Cancel','close')}</div>`);}else if(E.obj(value.activities)&&E.obj(value.rpg)){prepared={kind:'legacy',value};legacyDialog(value);}else if(value.weeks&&value.rpg){configDraft=JSON.stringify(value,null,2);switchView('config');configPreview(value);}else throw Error('Unrecognized file. Import a schema 8 full backup, a legacy progress save, or a complete configuration.');}
function legacyDialog(value){prepared={kind:'legacy',value};openDialog('Migrate legacy progress safely',`<p>v7.8 stored activities by array position. Its progress export did not contain the configuration, so this file alone cannot prove which activity each position meant.</p><form id="legacyForm"><label class="check"><input type="checkbox" name="original">I confirm this save used the exact unchanged plan in the supplied v7.8 HTML.</label><p class="small muted">Check this only if true. Otherwise positional activity, resource and cycle records go to recovery for manual review. Side Quests, Academy and named companies use identifiable matches. Ambiguous matches are never guessed.</p><p>Legacy XP, stats, installations and reward history become a preserved opening balance. New events use reversible rules. Your original save remains exportable for rollback.</p><div class="dialog-actions"><button class="primary" type="submit">Preview migration</button>${btn('Cancel','close')}</div></form>`);}
function recoveryDialog(){const p=bundle.progress,activeIds=new Set(E.all(bundle.config).map(a=>a.id)),archived=Object.keys(p.records).filter(id=>!activeIds.has(id));openDialog('Recovery archive',`<p class="muted">Unmatched data is retained in every full backup. Manual mapping never overwrites an existing record. Original legacy data remains available after mapping.</p><div class="row">${btn('Export recovery data','recovery-export')}${p.migration?btn('Export original legacy save','legacy-export'):''}</div>${p.recovery.map(q=>`<details class="entry"><summary>${esc(q.kind+' · '+q.key)} · ${q.resolved?'mapped to '+esc(q.targetId):'needs review'}</summary><p class="small muted">${esc(q.reason)}</p><pre class="prewrap small">${esc(JSON.stringify(q.value,null,2))}</pre>${q.kind==='activity'&&!q.resolved?`<form data-form="mapping" data-id="${q.id}"><label>Explicitly map to<select name="targetId">${options([['','Choose an activity'],...E.all(bundle.config).filter(a=>!p.records[a.id]).map(a=>[a.id,a.title+' ['+a.id+']'])],'')}</select></label><button type="submit">Save mapping</button></form>`:''}</details>`).join('')||'<p class="muted">No unmatched legacy records.</p>'}<div class="entry"><h3>Activities outside the active config</h3><p class="small muted">Restore the same config ID to resume. These records and awards remain intact.</p>${archived.map(id=>`<p class="small">${esc(id)} · ${esc(p.events[id]?.title||p.records[id].note||'preserved record')}</p>`).join('')||'<p class="muted">None.</p>'}</div>`);}
function portfolio(){const p=bundle.progress,r=E.progression(bundle);const rows=[`# ${p.profile.name||'Operative'} · Learning portfolio`,`\n${p.profile.missionStatement}`,`\n${r.totalCompleted} activities completed. ${r.credsEarned} credentials recorded with issuer/reference. All evidence is self-reported.`, '\n## Demonstrated skills'];for(const [id,x]of Object.entries(p.records))if(x.completed&&x.demonstrated&&(x.note||x.link||x.checkpoint))rows.push(`\n### ${E.all(bundle.config).find(a=>a.id===id)?.title||id}\n${x.note||''}\n${x.link||''}\n${x.checkpoint||''}`);rows.push('\n## Projects');bundle.config.projects.forEach(project=>{const d=p.projects[project.id];if(d)rows.push(`\n### ${project.title} — ${d.status}\nTarget (not achieved): ${project.metrics}\nAchieved results: ${d.actualMetrics||'No results recorded'}\n${[d.github,d.demo,d.video].filter(Boolean).join('\n')}`);});rows.push('\n## Credentials');Object.values(p.credentials).filter(x=>x.active).forEach(x=>rows.push(`- ${x.title} · ${x.issuer} · ${x.reference} · ${x.date}`));rows.push('\n## Reflections');p.retrospectives.forEach(x=>rows.push(`\n### After cycle ${x.atWeek} · ${x.date}\n${x.text}`));download('Mission_Control_Portfolio_'+E.day()+'.md',rows.join('\n'),'text/markdown');}
async function action(name,id,element){switch(name){
 case 'view':switchView(id);break;case 'close':closeDialog();break;
 case 'export':download('Mission_Control_backup_'+E.day()+'.json',bundle);break;
 case 'export-pending':if(pending)download('Mission_Control_UNSAVED_'+E.day()+'.json',pending);break;
 case 'retry':if(pending&&save(pending)){closeDialog();render();}break;
 case 'discard':pending=null;notice='Pending edits discarded. The last saved bundle is active.';status(bundle.savedAt?'Last saved bundle active':'Ready · not yet saved');render();break;
 case 'export-damaged':download('Mission_Control_original_recovery.txt',damagedRaw??'Storage could not be read.','text/plain');break;
 case 'recover-fresh':{const fresh=E.fresh(CONFIG);if(damagedRaw!==null)fresh.progress.recovery.push({id:E.uid('recovery'),kind:'malformed-storage',key:E.KEY,value:damagedRaw,reason:'Original text before explicit fresh start',resolved:false});readBlocked=false;if(save(fresh,{checkpoint:true})){closeDialog();render();}break;}
 case 'previous':try{const raw=localStorage.getItem(E.KEY+'_previous');if(!raw)throw Error('No previous snapshot is available. Import a downloaded full backup.');importPreview(E.parse(raw));}catch(e){showError(e.message);}break;
 case 'import':$('importFile').value='';$('importFile').click();break;
 case 'activity':activityDialog(id);break;
 case 'cycle':mutate(n=>{n.progress.settings.activeCycle=id;});break;
 case 'complete':{const was=E.record(bundle,id).completed,ok=mutate(n=>{if(was){captureEvidence(n,id);E.complete(n,id,false);}else{E.complete(n,id,true);captureEvidence(n,id);}});if(ok){if(!was&&!bundle.progress.settings.quiet&&bundle.progress.settings.celebrate)toast('Mission recorded · '+(bundle.progress.events[id]?.xp||0)+' XP');activityDialog(id);}break;}
 case 'defer':if($('evidenceForm')&&dialogActivity===id){if(!mutate(n=>captureEvidence(n,id)))break;}deferDialog(id);break;
 case 'resume':if(mutate(n=>E.defer(n,id,false))){activityDialog(id);}break;
 case 'undo-session':{const activity=bundle.progress.sessions.find(s=>s.id===id)?.activityId;if(mutate(n=>{const s=n.progress.sessions.find(s=>s.id===id);if(!s?.active)return false;s.active=false;}))activityDialog(activity);break;}
 case 'bulk':{const w=bundle.config.weeks.find(w=>w.id===id);openDialog('Review bulk completion',`<p>Only select work you actually finished. This records activity completion, not hours, demonstrated skills or credentials. Every award can be undone individually.</p><form id="bulkForm" data-id="${id}">${w.activities.filter(a=>!E.record(bundle,a.id).completed).map(a=>`<label class="check"><input type="checkbox" name="ids" value="${a.id}">${esc(a.name)} ${a.stretch?'(optional stretch)':''}</label>`).join('')}<div class="dialog-actions"><button type="submit" class="primary">Complete selected activities</button>${btn('Cancel','close')}</div></form>`);break;}
 case 'quest-filter':filters.quest=id;render();break;case 'leadership-filter':filters.leadership=id;render();break;
 case 'resource-status':mutate(n=>{const list=['N/A','Started','Completed'],old=n.progress.resources[id]||'N/A';n.progress.resources[id]=list[(list.indexOf(old)+1)%list.length];});break;
 case 'add-task':mutate(n=>{const p=n.config.projects.find(p=>p.id===id),d=n.progress.projects[id]||(n.progress.projects[id]=E.clone(projectData(p)));d.subtasks.push({id:E.uid('task'),text:'New checkpoint',done:false});});break;
 case 'delete-task':{const [pid,tid]=id.split('|');mutate(n=>{const p=n.config.projects.find(p=>p.id===pid),d=n.progress.projects[pid]||(n.progress.projects[pid]=E.clone(projectData(p)));d.subtasks=d.subtasks.filter(t=>t.id!==tid);});break;}
 case 'add-company':mutate(n=>{n.progress.jobs[E.uid('job')]={company:'New target',track:id,custom:true,status:'Not Applied',dateApplied:'',contact:'',notes:''};});break;
 case 'retro':retroDialog(id);break;
 case 'credential-undo':mutate(n=>{n.progress.credentials[id].active=false;});break;
 case 'augmentation':mutate(n=>{const a=n.config.rpg.augmentations.find(a=>a.id===id);if(!a||!['overclock','resource'].includes(id))throw Error('This augmentation is cosmetic.');const old=n.progress.purchases.find(x=>x.augmentationId===id);if(old?.active){old.active=false;return;}if(E.progression(n).augPoints<1)throw Error('No augmentation points are available yet.');if(old)old.active=true;else n.progress.purchases.push({id:E.uid('purchase'),augmentationId:id,active:true,at:new Date().toISOString()});});break;
 case 'portfolio':portfolio();break;
 case 'validate-config':configDraft=$('configEditor').value;configPreview(E.parse(configDraft));break;
 case 'confirm-config':if(prepared?.kind==='config'&&!pending){const n=E.applyConfig(bundle,prepared.value);if(save(n,{checkpoint:true,message:'Configuration and progress saved'})){configDraft=null;prepared=null;closeDialog();render();}}break;
 case 'default-config':configDraft=JSON.stringify(CONFIG,null,2);$('configEditor').value=configDraft;configPreview(E.clone(CONFIG));break;
 case 'load-config':configDraft=null;$('configEditor').value=JSON.stringify(bundle.config,null,2);break;
 case 'export-config':download('Mission_Control_config_v8.json',bundle.config);break;
 case 'new-id':{const newId=E.uid('act');openDialog('New stable activity ID',`<p>Use this ID for a new activity; keep it when you reorder or move that activity.</p>${field('New ID','newId',newId,'text','readonly')}`);break;}
 case 'legacy':legacyDialog(E.parse(legacyRaw));break;
 case 'confirm-backup':if(prepared?.kind==='backup'){const wasBlocked=readBlocked;readBlocked=false;const n=E.clone(prepared.value);if(wasBlocked&&damagedRaw!==null)n.progress.recovery.push({id:E.uid('recovery'),kind:'malformed-storage',key:E.KEY,value:damagedRaw,reason:'Preserved before backup restoration',resolved:false});if(save(n,{checkpoint:true,message:'Full backup restored'})){prepared=null;configDraft=null;closeDialog();render();}}break;
 case 'confirm-migration':if(prepared?.kind==='migration'&&save(prepared.value,{checkpoint:true,message:'Migration saved with recovery archive'})){prepared=null;closeDialog();render();}break;
 case 'legacy-export':if(bundle.progress.migration)download('Mission_Control_original_v7_save.json',bundle.progress.migration.raw);break;
 case 'recovery':recoveryDialog();break;
 case 'recovery-export':download('Mission_Control_recovery_'+E.day()+'.json',{recovery:bundle.progress.recovery,migration:bundle.progress.migration,archivedRecords:bundle.progress.records,events:bundle.progress.events});break;
 }}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)Promise.resolve(action(b.dataset.action,b.dataset.id,b)).catch(err=>showError(err.message));});
document.addEventListener('submit',e=>{const f=e.target;if(!(f instanceof HTMLFormElement))return;e.preventDefault();const d=new FormData(f),id=f.dataset.id;try{
 if(f.id==='plannerForm'){mutate(n=>{Object.assign(n.progress.settings,{weeklyHours:Number(d.get('weeklyHours')),sessionMinutes:Number(d.get('sessionMinutes')),format:d.get('format'),preferredTracks:d.getAll('preferredTracks'),activeCycle:d.get('activeCycle'),includeStretch:d.has('includeStretch')});});}
 else if(f.id==='planFilter'){Object.assign(filters,Object.fromEntries(d));render();}
 else if(f.id==='resourceSearch'){filters.resource=d.get('query');render();}
 else if(f.id==='profileForm'){mutate(n=>{Object.assign(n.progress.profile,{name:d.get('name'),callsign:d.get('callsign'),classId:d.get('classId'),missionStatement:d.get('missionStatement')});n.progress.settings.quiet=d.has('quiet');n.progress.settings.celebrate=d.has('celebrate');});}
 else if(f.id==='evidenceForm'){if(mutate(n=>captureEvidence(n,id)))activityDialog(id);}
 else if(f.id==='sessionForm'){if(mutate(n=>{captureEvidence(n,id);return E.addSession(n,id,Number(d.get('minutes')),d.get('note'),f.dataset.token);})){activityDialog(id);toast('Session saved. Completion unchanged.');}}
 else if(f.id==='deferForm'){if(mutate(n=>E.defer(n,id,true,d.get('reason'))))closeDialog();}
 else if(f.id==='bulkForm'){if(mutate(n=>E.bulk(n,d.getAll('ids'),true)>0))closeDialog();}
 else if(f.id==='retroForm'){if(mutate(n=>{const text=String(d.get('text')).trim();if(!text)throw Error('Write a reflection before saving.');const old=n.progress.retrospectives.find(r=>String(r.atWeek)===id),data={atWeek:Number(id),text,date:E.day()};if(old)Object.assign(old,data);else n.progress.retrospectives.push(data);})){closeDialog();}}
 else if(f.id==='credentialForm'){if(mutate(n=>{const issuer=String(d.get('issuer')).trim(),reference=String(d.get('reference')).trim(),date=String(d.get('date'));if(!issuer||!reference||!E.validDay(date)||date>E.day())throw Error('Enter issuer, certificate reference and a valid earned date.');const key='credential-'+E.hash(issuer.toLowerCase()+'|'+reference.toLowerCase()).toString(36),a=E.all(n.config).find(a=>a.id===id);n.progress.credentials[key]={id:key,title:a.title,activityId:id,issuer,reference,date,active:true};})){activityDialog(id);toast('Credential evidence recorded.');}}
 else if(f.id==='legacyForm'){const n=E.migrate(prepared.value,CONFIG,d.has('original'));prepared={kind:'migration',value:n};openDialog('Review migration result',`<p>${Object.keys(n.progress.records).length} matched activity records · ${n.progress.recovery.length} records held for recovery.</p><p>${n.progress.baseline.xp} legacy XP preserved. Your original JSON values are included in every backup.</p><p class="muted">No accomplishment has been invented. Uncertain positional records remain unmapped unless you explicitly confirmed the original plan.</p><div class="dialog-actions">${btn('Save migrated bundle','confirm-migration','','primary')}${btn('Cancel','close')}</div>`);}
 else if(f.dataset.form==='cycleNotes'){mutate(n=>{n.progress.cycleNotes[id]=d.get('text');});}
 else if(f.dataset.form==='project'){mutate(n=>{for(const key of ['github','demo','video'])if(d.get(key)&&!E.safeURL(d.get(key)))throw Error('Project links must use http:// or https://.');const p=n.config.projects.find(p=>p.id===id),data=n.progress.projects[id]||(n.progress.projects[id]=E.clone(projectData(p)));Object.assign(data,Object.fromEntries(d));});}
 else if(f.dataset.form==='job'){mutate(n=>{n.progress.jobs[id]={...n.progress.jobs[id],...Object.fromEntries(d),track:f.dataset.track};});}
 else if(f.dataset.form==='mapping'){if(mutate(n=>E.resolveRecovery(n,id,d.get('targetId'))))recoveryDialog();}
 }catch(err){showError(err.message);}});
document.addEventListener('change',e=>{const x=e.target;if(x.dataset.taskProject||x.dataset.editProject){const pid=x.dataset.taskProject||x.dataset.editProject,tid=x.dataset.taskId||x.dataset.editTask;mutate(n=>{const p=n.config.projects.find(p=>p.id===pid),d=n.progress.projects[pid]||(n.progress.projects[pid]=E.clone(projectData(p))),t=d.subtasks.find(t=>t.id===tid);if(x.dataset.taskProject)t.done=x.checked;else t.text=x.value;});}});
document.addEventListener('input',e=>{if(e.target.id==='configEditor')configDraft=e.target.value;});
$('menuButton').onclick=()=>openDialog('All sections',`<nav class="nav" aria-label="All sections">${navMarkup()}</nav><div class="dialog-actions">${btn('Full backup','export')}${btn('Import / restore','import')}</div>`);
$('dialog').addEventListener('close',()=>{const target=lastFocus?.isConnected?lastFocus:lastFocusData?[...document.querySelectorAll('#page [data-action],#nav [data-action]')].find(x=>x.dataset.action===lastFocusData.action&&x.dataset.id===lastFocusData.id):null;(target||$('content')).focus({preventScroll:true});});
$('dialog').addEventListener('keydown',e=>{if(e.key!=='Tab')return;const list=[...$('dialog').querySelectorAll('a[href],button,input,select,textarea,summary,[tabindex]')].filter(x=>!x.disabled&&x.tabIndex>=0&&x.getClientRects().length);if(!list.length){e.preventDefault();return;}const first=list[0],last=list.at(-1);if(e.shiftKey&&(document.activeElement===first||!list.includes(document.activeElement))){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||!list.includes(document.activeElement))){e.preventDefault();first.focus();}});
$('importFile').onchange=async()=>{const f=$('importFile').files[0];if(!f)return;try{if(f.size>25*1024*1024)throw Error('This file is larger than 25 MB. Keep a copy and reduce embedded legacy archives before importing.');importPreview(E.parse(await f.text()));}catch(e){showError(e.message);}};
const adjustViewport=()=>document.documentElement.style.setProperty('--visible-height',(window.visualViewport?.height||window.innerHeight)+'px');window.visualViewport?.addEventListener('resize',adjustViewport);adjustViewport();
window.addEventListener('beforeunload',e=>{if(pending){e.preventDefault();e.returnValue='';}});
window.addEventListener('storage',e=>{if(e.key===E.KEY&&e.newValue!==lastRaw){notice='Another tab changed the save. Export this view if needed, then reload to use the newer bundle.';status('Save changed in another tab',true);renderNotice();}});
let lastDay=E.day();document.addEventListener('visibilitychange',()=>{if(!document.hidden&&lastDay!==E.day()){lastDay=E.day();render();}});setInterval(()=>{if(lastDay!==E.day()){lastDay=E.day();if(!$('dialog').open)render();}},30000);
try{lastRaw=localStorage.getItem(E.KEY);if(lastRaw){bundle=E.validateBundle(E.parse(lastRaw));status('Loaded from this device');}else{legacyRaw=localStorage.getItem(E.LEGACY_KEY);if(legacyRaw)notice='A v7 legacy save is available on this browser. Review its identity mappings before migration.';}}
catch(e){damagedRaw=lastRaw;readBlocked=true;notice=e.message+' Original storage is left intact. Import a good backup or explicitly start fresh with a recovery copy.';status('Storage unavailable or malformed',true);}
render();
window.MC={Engine:E,snapshot:()=>E.clone(bundle),pending:()=>pending?E.clone(pending):null,version:'8.0.0'};
})();
